export const ExpressPort = process.env.EXPRESS_PORT ?? 5623;
export const Discord_Prefix = "!";
export const Discord_Token = process.env.DISCORD_TOKEN ?? "";
export const callbackURL = "http://localhost:5623/api/oauth/callback",
    clientID = process.env.DISCORD_CLIENT_ID ?? "", 
    clientSecret = process.env.DISCORD_CLIENT_SECRET ?? "", 
    redirectUri = "https://localhost:5623/"
export const SecretAuth = process.env.SECRETAUTH ?? ""
export const NTIDiscordID = "589051744030294017";