export const ExpressPort = process.env.EXPRESS_PORT ?? 5623;
export const Discord_Prefix = "!";
export const Admin_Role_Id = "";
export const Discord_Token = process.env.DISCORD_TOKEN ?? "";
export const callbackURL = process.env.CALLBACK_URL ?? "http://localhost:5623/api/oauth/callback",
    clientID = process.env.DISCORD_CLIENT_ID ?? "", 
    clientSecret = process.env.DISCORD_CLIENT_SECRET ?? "", 
    redirectUri = process.env.REDIRECT_URI ?? "https://localhost:5623/"
export const SecretAuth = process.env.SECRETAUTH ?? ""
export const NTIDiscordID = "835552025839665173";
export const MongoDB_URL = process.env.MONGODB_URL ?? "";